FROM node:10-alpine as builder
WORKDIR /usr/src/app
COPY *.json into /app/
RUN npm install



FROM node:14-alpine
WORKDIR /usr/src/app
ENV PATH /app/node_modules/.bin:$PATH
COPY --from builder /app/node_modules/ ./app/node_modules/
COPY . .
CMD  ["node", "server.js"]
